### ISSUE TITLE
Interference between Kia UVO plugin and Hyundai bluelink in jeedom

### ISSUE THREAD

**Issue by monfiston** [neoPix/jeedom-hyundaibluelink-documentation#1]
hello
I bought the Kia UVO and Hyundai bluelink plugins because I have 1 car of these 2 brands
separately the 2 plugins work well
but the 2 sets, the information is mixed between the 2 vehicles
as you can see on the 2 objects, the information is identical!
[
![Screenshot_20221002-221025_Chrome](https://user-images.githubusercontent.com/109015014/193474226-8f23c2be-6970-48d3-94dc-393ce73feb56.jpg)

voici la configuration que j’ai fait:
![3](https://user-images.githubusercontent.com/109015014/193449401-e4416fb6-f047-4e2a-be8b-0381fc8cc1b3.jpg)
![4](https://user-images.githubusercontent.com/109015014/193449402-e98c9898-fe3b-4f20-8d8a-9c074e3ef27f.jpg)
comment je peux résoudre le pb?

source:https://community.jeedom.com/t/interference-entre-le-plugin-kia-uvo-et-hyundai-bluelink/91760

**Comment by monfiston** [comment]
hello
did you have time to look at the pb
Cordially

**Comment by neoPix** [comment]
Hi @monfiston.
Also had the issue while testing on my own. I fixed it so it should be working in the latests releases.
